// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (m *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(m, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

func (m *UserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *UserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type User struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string    `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	NoticeList           []*Notice `protobuf:"bytes,3,rep,name=noticeList,proto3" json:"noticeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetNoticeList() []*Notice {
	if m != nil {
		return m.NoticeList
	}
	return nil
}

type Notice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	FromUserId           string   `protobuf:"bytes,5,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notice) Reset()         { *m = Notice{} }
func (m *Notice) String() string { return proto.CompactTextString(m) }
func (*Notice) ProtoMessage()    {}
func (*Notice) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Notice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notice.Unmarshal(m, b)
}
func (m *Notice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notice.Marshal(b, m, deterministic)
}
func (m *Notice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notice.Merge(m, src)
}
func (m *Notice) XXX_Size() int {
	return xxx_messageInfo_Notice.Size(m)
}
func (m *Notice) XXX_DiscardUnknown() {
	xxx_messageInfo_Notice.DiscardUnknown(m)
}

var xxx_messageInfo_Notice proto.InternalMessageInfo

func (m *Notice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notice) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notice) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notice) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Notice) GetFromUserId() string {
	if m != nil {
		return m.FromUserId
	}
	return ""
}

func (m *Notice) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type NoticeReq struct {
	Notice               *Notice  `protobuf:"bytes,1,opt,name=notice,proto3" json:"notice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeReq) Reset()         { *m = NoticeReq{} }
func (m *NoticeReq) String() string { return proto.CompactTextString(m) }
func (*NoticeReq) ProtoMessage()    {}
func (*NoticeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *NoticeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeReq.Unmarshal(m, b)
}
func (m *NoticeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeReq.Marshal(b, m, deterministic)
}
func (m *NoticeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeReq.Merge(m, src)
}
func (m *NoticeReq) XXX_Size() int {
	return xxx_messageInfo_NoticeReq.Size(m)
}
func (m *NoticeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeReq proto.InternalMessageInfo

func (m *NoticeReq) GetNotice() *Notice {
	if m != nil {
		return m.Notice
	}
	return nil
}

type NoticeResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Notice               *Notice  `protobuf:"bytes,3,opt,name=notice,proto3" json:"notice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeResp) Reset()         { *m = NoticeResp{} }
func (m *NoticeResp) String() string { return proto.CompactTextString(m) }
func (*NoticeResp) ProtoMessage()    {}
func (*NoticeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *NoticeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeResp.Unmarshal(m, b)
}
func (m *NoticeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeResp.Marshal(b, m, deterministic)
}
func (m *NoticeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeResp.Merge(m, src)
}
func (m *NoticeResp) XXX_Size() int {
	return xxx_messageInfo_NoticeResp.Size(m)
}
func (m *NoticeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeResp.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeResp proto.InternalMessageInfo

func (m *NoticeResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NoticeResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *NoticeResp) GetNotice() *Notice {
	if m != nil {
		return m.Notice
	}
	return nil
}

func init() {
	proto.RegisterType((*UserReq)(nil), "user.UserReq")
	proto.RegisterType((*UserResp)(nil), "user.UserResp")
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*User)(nil), "user.user")
	proto.RegisterType((*Notice)(nil), "user.notice")
	proto.RegisterType((*NoticeReq)(nil), "user.NoticeReq")
	proto.RegisterType((*NoticeResp)(nil), "user.NoticeResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5f, 0x6b, 0xe2, 0x40,
	0x10, 0xbf, 0x18, 0x13, 0x93, 0xc9, 0x9d, 0x77, 0x0c, 0xc7, 0x11, 0x7c, 0x10, 0x2f, 0xdc, 0x83,
	0xf7, 0x07, 0x41, 0xfd, 0x04, 0xf7, 0x50, 0x4a, 0xa1, 0xf8, 0xb0, 0xa5, 0xef, 0x4d, 0x93, 0xa9,
	0x04, 0x34, 0xab, 0xbb, 0x6b, 0x4b, 0x3f, 0x4a, 0xa1, 0x1f, 0xb6, 0xec, 0x4e, 0x62, 0x15, 0x2a,
	0x14, 0xfa, 0x22, 0xfb, 0xfb, 0x33, 0xf3, 0xdb, 0x99, 0x35, 0x00, 0x3b, 0x4d, 0x6a, 0xb2, 0x51,
	0xd2, 0x48, 0xec, 0xda, 0x73, 0xf6, 0x1b, 0x7a, 0xd7, 0x9a, 0x94, 0xa0, 0x2d, 0x0e, 0xc1, 0x51,
	0xa9, 0x37, 0xf2, 0xc6, 0xc9, 0x0c, 0x26, 0xce, 0x6b, 0x7f, 0x04, 0x5b, 0x97, 0x10, 0xb1, 0x55,
	0x6f, 0x30, 0x85, 0x9e, 0xde, 0x15, 0x05, 0x69, 0xed, 0xec, 0x91, 0x68, 0x21, 0xfe, 0x84, 0x80,
	0x94, 0x92, 0x2a, 0xed, 0xb8, 0x36, 0x09, 0xb7, 0x39, 0xb3, 0x94, 0x60, 0x65, 0x1f, 0xe4, 0x9f,
	0x08, 0x9a, 0x43, 0xe0, 0xfc, 0x88, 0xd0, 0x2d, 0x64, 0x49, 0x2e, 0x22, 0x10, 0xee, 0x8c, 0x3f,
	0x20, 0x2c, 0xc9, 0xe4, 0xd5, 0xca, 0x05, 0xc4, 0xa2, 0x41, 0xd9, 0x0d, 0x37, 0xc5, 0x3e, 0x74,
	0xaa, 0xd2, 0x55, 0xc4, 0xa2, 0x53, 0x95, 0x38, 0x80, 0xc8, 0xf2, 0x8b, 0x7c, 0x4d, 0x4d, 0xc5,
	0x1e, 0xe3, 0x3f, 0x80, 0x5a, 0x9a, 0xaa, 0xa0, 0xcb, 0x4a, 0x9b, 0xd4, 0x1f, 0xf9, 0xe3, 0x64,
	0xf6, 0x99, 0xaf, 0xc3, 0xbc, 0x38, 0xd0, 0xb3, 0x67, 0x0f, 0x42, 0x86, 0x6f, 0x85, 0x14, 0xb9,
	0xa1, 0xa5, 0x54, 0x8f, 0x6d, 0x48, 0x8b, 0xf1, 0x3b, 0x04, 0xa6, 0x32, 0x2b, 0x72, 0xe3, 0xc6,
	0x82, 0x81, 0x5d, 0x60, 0x21, 0x6b, 0x43, 0xb5, 0x49, 0xbb, 0x8e, 0x6f, 0x21, 0x0e, 0x01, 0xee,
	0x94, 0x5c, 0xdb, 0x55, 0x5f, 0x94, 0x69, 0xe0, 0xc4, 0x03, 0xc6, 0x2e, 0x60, 0xc7, 0x5a, 0xc8,
	0x0b, 0x60, 0x94, 0x4d, 0x21, 0x5e, 0xf0, 0xa5, 0x69, 0x8b, 0xbf, 0xda, 0xab, 0x36, 0xaf, 0x79,
	0x3c, 0x55, 0xa3, 0x65, 0x12, 0xa0, 0x2d, 0xf9, 0xe8, 0x9b, 0xbe, 0x06, 0xfa, 0xa7, 0x03, 0x67,
	0x4f, 0x1e, 0x24, 0x76, 0x8c, 0xff, 0x75, 0xb9, 0xa0, 0x07, 0x8d, 0x7f, 0x21, 0xba, 0xca, 0xef,
	0xc9, 0x52, 0xf8, 0x85, 0x2b, 0x9a, 0x7f, 0xe3, 0xa0, 0x7f, 0x08, 0xf5, 0x26, 0xfb, 0x84, 0x7f,
	0xa0, 0x77, 0x4e, 0xe6, 0x7d, 0xde, 0x29, 0x80, 0x6d, 0xcc, 0xd3, 0xe1, 0x57, 0xd6, 0xf7, 0xeb,
	0x19, 0x7c, 0x3b, 0x26, 0x6c, 0xc9, 0x6d, 0xe8, 0x3e, 0x8b, 0xf9, 0x4b, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x63, 0xb6, 0x63, 0x83, 0x24, 0x03, 0x00, 0x00,
}
