// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hello_world.proto

package micro_pure_helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for HelloWorld service

type HelloWorldService interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...client.CallOption) (*EchoResponse, error)
	//    rpc Print(google.protobuf.Empty) returns (PrintResponse){}
	Print(ctx context.Context, in *PrintRequest, opts ...client.CallOption) (*PrintResponse, error)
}

type helloWorldService struct {
	c    client.Client
	name string
}

func NewHelloWorldService(name string, c client.Client) HelloWorldService {
	return &helloWorldService{
		c:    c,
		name: name,
	}
}

func (c *helloWorldService) Echo(ctx context.Context, in *EchoRequest, opts ...client.CallOption) (*EchoResponse, error) {
	req := c.c.NewRequest(c.name, "HelloWorld.Echo", in)
	out := new(EchoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloWorldService) Print(ctx context.Context, in *PrintRequest, opts ...client.CallOption) (*PrintResponse, error) {
	req := c.c.NewRequest(c.name, "HelloWorld.Print", in)
	out := new(PrintResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloWorld service

type HelloWorldHandler interface {
	Echo(context.Context, *EchoRequest, *EchoResponse) error
	//    rpc Print(google.protobuf.Empty) returns (PrintResponse){}
	Print(context.Context, *PrintRequest, *PrintResponse) error
}

func RegisterHelloWorldHandler(s server.Server, hdlr HelloWorldHandler, opts ...server.HandlerOption) error {
	type helloWorld interface {
		Echo(ctx context.Context, in *EchoRequest, out *EchoResponse) error
		Print(ctx context.Context, in *PrintRequest, out *PrintResponse) error
	}
	type HelloWorld struct {
		helloWorld
	}
	h := &helloWorldHandler{hdlr}
	return s.Handle(s.NewHandler(&HelloWorld{h}, opts...))
}

type helloWorldHandler struct {
	HelloWorldHandler
}

func (h *helloWorldHandler) Echo(ctx context.Context, in *EchoRequest, out *EchoResponse) error {
	return h.HelloWorldHandler.Echo(ctx, in, out)
}

func (h *helloWorldHandler) Print(ctx context.Context, in *PrintRequest, out *PrintResponse) error {
	return h.HelloWorldHandler.Print(ctx, in, out)
}
